import { shadcn } from "@clerk/ui/themes"
import type { Metadata } from "next"
import { ClerkProvider } from "@clerk/nextjs"
import { Mulish } from "next/font/google"
import "./globals.css"

const mulish = Mulish({
  subsets: ["latin-ext"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${mulish.className} dark h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <ClerkProvider
          afterSignOutUrl="/login"
          appearance={{
            theme: shadcn,
          }}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  )
}
